_BASE_: "Base-FCOS.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "R-50.pkl"
  RESNETS:
    DEPTH: 50
  FCOS:
    NUM_CLASSES: 3
INPUT:
  MIN_SIZE_TRAIN: (800,)
DATASETS:
  TRAIN: ("fruits_nuts",)
  TEST: ("fruits_nuts", )
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
OUTPUT_DIR: "output/fcos/R_50_1x"
